### ISSUE TITLE
跟hulutool比那个好用啊？

### ISSUE THREAD

**Issue by zbzbzb022** [ifeilong/feilong-core#767]
hulutool已经很强大了

**Comment by lycbug666** [comment]
> hulutool已经很强大了

hulutool的链接能给个吗?

**Comment by zbzbzb022** [comment]
去github上搜啊


| |
周斌
|
|
邮箱：zbzbzb022@163.com
|

签名由 网易邮箱大师 定制

在2019年04月23日 14:25，Long Yichen 写道：

hulutool已经很强大了

hulutool的链接能给个吗?

**Comment by fangjinuo** [comment]
还是看看这个吧：
[langx-java](https://github.com/fangjinuo/langx-java)

**Comment by fangjinuo** [comment]
还是看看这个吧：
[langx-java](https://github.com/fangjinuo/langx-java)
